// <auto-generated />
using System;
using ECommerceAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerceAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260601100115_AddCategoriesCoupons")]
    partial class AddCategoriesCoupons
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerceAPI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gadgets, devices, and tech accessories",
                            Icon = "💻",
                            IsActive = true,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fashion, apparel, and accessories",
                            Icon = "👕",
                            IsActive = true,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Books, ebooks, and educational content",
                            Icon = "📚",
                            IsActive = true,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Home decor, kitchen, and lifestyle products",
                            Icon = "🏠",
                            IsActive = true,
                            Name = "Home"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mobile phones and accessories",
                            Icon = "📱",
                            IsActive = true,
                            Name = "Smartphones",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Laptops, notebooks, and ultrabooks",
                            Icon = "💻",
                            IsActive = true,
                            Name = "Laptops",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Shoes, sneakers, and sandals",
                            Icon = "👟",
                            IsActive = true,
                            Name = "Footwear",
                            ParentId = 2
                        });
                });

            modelBuilder.Entity("ECommerceAPI.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxUses")
                        .HasColumnType("int");

                    b.Property<decimal>("MinOrderAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsedCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("ECommerceAPI.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ECommerceAPI.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("ECommerceAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 6, 1, 10, 1, 14, 826, DateTimeKind.Utc).AddTicks(2170),
                            Description = "High-performance laptop with Intel Core i7, 16GB RAM, 512GB SSD. Perfect for professionals and creators.",
                            ImageUrl = "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&h=400&fit=crop&auto=format",
                            IsActive = true,
                            Name = "Laptop Pro 15\"",
                            Price = 85000m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 2,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 6, 1, 10, 1, 14, 826, DateTimeKind.Utc).AddTicks(2178),
                            Description = "Precision wireless mouse with ergonomic design, 3-month battery life, and silent click technology.",
                            ImageUrl = "https://images.unsplash.com/photo-1527814050087-3793815479db?w=600&h=400&fit=crop&auto=format",
                            IsActive = true,
                            Name = "Wireless Ergonomic Mouse",
                            Price = 1299m,
                            Stock = 150
                        },
                        new
                        {
                            Id = 3,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 6, 1, 10, 1, 14, 826, DateTimeKind.Utc).AddTicks(2181),
                            Description = "RGB backlit mechanical keyboard with tactile brown switches, anti-ghosting, and detachable USB-C cable.",
                            ImageUrl = "https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=600&h=400&fit=crop&auto=format",
                            IsActive = true,
                            Name = "Mechanical Gaming Keyboard",
                            Price = 3999m,
                            Stock = 75
                        },
                        new
                        {
                            Id = 4,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 6, 1, 10, 1, 14, 826, DateTimeKind.Utc).AddTicks(2184),
                            Description = "Industry-leading noise cancellation with 30-hour battery life. Crystal clear audio for music and calls.",
                            ImageUrl = "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&h=400&fit=crop&auto=format",
                            IsActive = true,
                            Name = "Noise Cancelling Headphones",
                            Price = 25999m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 5,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 6, 1, 10, 1, 14, 826, DateTimeKind.Utc).AddTicks(2185),
                            Description = "Latest flagship smartphone with 6.7\" OLED display, 108MP camera, 5G connectivity, and 5000mAh battery.",
                            ImageUrl = "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&h=400&fit=crop&auto=format",
                            IsActive = true,
                            Name = "Smartphone Pro Max",
                            Price = 79999m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 6,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 6, 1, 10, 1, 14, 826, DateTimeKind.Utc).AddTicks(2187),
                            Description = "Ultra-sharp 4K IPS display with 99% sRGB color accuracy, USB-C 65W power delivery, and ergonomic stand.",
                            ImageUrl = "https://images.unsplash.com/photo-1527443224154-c4a573d5b5b1?w=600&h=400&fit=crop&auto=format",
                            IsActive = true,
                            Name = "27\" 4K UHD Monitor",
                            Price = 28000m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 7,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 6, 1, 10, 1, 14, 826, DateTimeKind.Utc).AddTicks(2189),
                            Description = "Slim and powerful tablet with fast chip, 10.9\" Liquid Retina display, and all-day battery life.",
                            ImageUrl = "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600&h=400&fit=crop&auto=format",
                            IsActive = true,
                            Name = "Digital Tablet 10.9\"",
                            Price = 62999m,
                            Stock = 35
                        },
                        new
                        {
                            Id = 8,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 6, 1, 10, 1, 14, 826, DateTimeKind.Utc).AddTicks(2191),
                            Description = "Advanced health monitoring with ECG, blood oxygen tracking, crash detection, and always-on GPS.",
                            ImageUrl = "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&h=400&fit=crop&auto=format",
                            IsActive = true,
                            Name = "Smart Watch Series 9",
                            Price = 29999m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 9,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 6, 1, 10, 1, 14, 826, DateTimeKind.Utc).AddTicks(2193),
                            Description = "24.1MP DSLR with 18-55mm kit lens, 4K video, built-in Wi-Fi, and 45-point autofocus system.",
                            ImageUrl = "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=600&h=400&fit=crop&auto=format",
                            IsActive = true,
                            Name = "DSLR Camera Kit",
                            Price = 55000m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 10,
                            Category = "Clothing",
                            CreatedAt = new DateTime(2026, 6, 1, 10, 1, 14, 826, DateTimeKind.Utc).AddTicks(2195),
                            Description = "100% premium cotton t-shirt with a perfect relaxed fit. Breathable, durable, and effortlessly stylish.",
                            ImageUrl = "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&h=400&fit=crop&auto=format",
                            IsActive = true,
                            Name = "Classic White T-Shirt",
                            Price = 599m,
                            Stock = 500
                        },
                        new
                        {
                            Id = 11,
                            Category = "Clothing",
                            CreatedAt = new DateTime(2026, 6, 1, 10, 1, 14, 826, DateTimeKind.Utc).AddTicks(2196),
                            Description = "Stretch denim slim-fit jeans with modern tapered leg cut. Comfortable all-day wear in classic indigo wash.",
                            ImageUrl = "https://images.unsplash.com/photo-1542272604-787c3835535d?w=600&h=400&fit=crop&auto=format",
                            IsActive = true,
                            Name = "Slim Fit Denim Jeans",
                            Price = 1799m,
                            Stock = 200
                        },
                        new
                        {
                            Id = 12,
                            Category = "Clothing",
                            CreatedAt = new DateTime(2026, 6, 1, 10, 1, 14, 826, DateTimeKind.Utc).AddTicks(2198),
                            Description = "Full-grain leather moto jacket with zip-off sleeves, quilted lining, and premium YKK hardware.",
                            ImageUrl = "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&h=400&fit=crop&auto=format",
                            IsActive = true,
                            Name = "Genuine Leather Jacket",
                            Price = 8999m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 13,
                            Category = "Clothing",
                            CreatedAt = new DateTime(2026, 6, 1, 10, 1, 14, 826, DateTimeKind.Utc).AddTicks(2200),
                            Description = "Lightweight running shoes with responsive foam cushioning, breathable knit upper, and durable rubber outsole.",
                            ImageUrl = "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=400&fit=crop&auto=format",
                            IsActive = true,
                            Name = "Running Sneakers Pro",
                            Price = 4999m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 14,
                            Category = "Clothing",
                            CreatedAt = new DateTime(2026, 6, 1, 10, 1, 14, 826, DateTimeKind.Utc).AddTicks(2257),
                            Description = "Structured 6-panel cap with embroidered logo, curved brim, and adjustable snapback closure. One size fits all.",
                            ImageUrl = "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=600&h=400&fit=crop&auto=format",
                            IsActive = true,
                            Name = "Adjustable Baseball Cap",
                            Price = 699m,
                            Stock = 300
                        },
                        new
                        {
                            Id = 15,
                            Category = "Books",
                            CreatedAt = new DateTime(2026, 6, 1, 10, 1, 14, 826, DateTimeKind.Utc).AddTicks(2260),
                            Description = "A handbook of agile software craftsmanship by Robert C. Martin. Essential reading for every serious developer.",
                            ImageUrl = "https://images.unsplash.com/photo-1481627834876-b7833e8f84c4?w=600&h=400&fit=crop&auto=format",
                            IsActive = true,
                            Name = "Clean Code",
                            Price = 799m,
                            Stock = 200
                        },
                        new
                        {
                            Id = 16,
                            Category = "Books",
                            CreatedAt = new DateTime(2026, 6, 1, 10, 1, 14, 826, DateTimeKind.Utc).AddTicks(2262),
                            Description = "James Clear's guide to building good habits and breaking bad ones using tiny, incremental changes.",
                            ImageUrl = "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&h=400&fit=crop&auto=format",
                            IsActive = true,
                            Name = "Atomic Habits",
                            Price = 499m,
                            Stock = 300
                        },
                        new
                        {
                            Id = 17,
                            Category = "Books",
                            CreatedAt = new DateTime(2026, 6, 1, 10, 1, 14, 826, DateTimeKind.Utc).AddTicks(2263),
                            Description = "Eric Ries teaches how continuous innovation creates radically successful businesses. Must-read for entrepreneurs.",
                            ImageUrl = "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&h=400&fit=crop&auto=format",
                            IsActive = true,
                            Name = "The Lean Startup",
                            Price = 599m,
                            Stock = 250
                        },
                        new
                        {
                            Id = 18,
                            Category = "Home",
                            CreatedAt = new DateTime(2026, 6, 1, 10, 1, 14, 826, DateTimeKind.Utc).AddTicks(2265),
                            Description = "Set of 4 handcrafted ceramic mugs in earthy matte tones. Microwave and dishwasher safe. 350ml capacity.",
                            ImageUrl = "https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=600&h=400&fit=crop&auto=format",
                            IsActive = true,
                            Name = "Ceramic Coffee Mug Set",
                            Price = 899m,
                            Stock = 150
                        },
                        new
                        {
                            Id = 19,
                            Category = "Home",
                            CreatedAt = new DateTime(2026, 6, 1, 10, 1, 14, 826, DateTimeKind.Utc).AddTicks(2267),
                            Description = "Touch-controlled LED lamp with 5 brightness levels, 4000K color temperature, and USB-A charging port.",
                            ImageUrl = "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&h=400&fit=crop&auto=format",
                            IsActive = true,
                            Name = "LED Architect Desk Lamp",
                            Price = 1499m,
                            Stock = 80
                        },
                        new
                        {
                            Id = 20,
                            Category = "Home",
                            CreatedAt = new DateTime(2026, 6, 1, 10, 1, 14, 826, DateTimeKind.Utc).AddTicks(2269),
                            Description = "Luxury soy wax candles in 4 relaxing fragrances: Lavender, Vanilla, Sandalwood, and Ocean Breeze. 40hr burn time.",
                            ImageUrl = "https://images.unsplash.com/photo-1542621334-a254cf47733d?w=600&h=400&fit=crop&auto=format",
                            IsActive = true,
                            Name = "Scented Candle Gift Set",
                            Price = 999m,
                            Stock = 120
                        });
                });

            modelBuilder.Entity("ECommerceAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ECommerceAPI.Models.Category", b =>
                {
                    b.HasOne("ECommerceAPI.Models.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ECommerceAPI.Models.Order", b =>
                {
                    b.HasOne("ECommerceAPI.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECommerceAPI.Models.OrderItem", b =>
                {
                    b.HasOne("ECommerceAPI.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerceAPI.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerceAPI.Models.Category", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("ECommerceAPI.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("ECommerceAPI.Models.Product", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("ECommerceAPI.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
